ddpm_path: './output/DDPM/test/model/checkpoint.pth'
bb_path: './output/BrownianBridge/test/model/checkpoint.pth'
ddpm_config: 'DDPM.yml'
bb_config: 'BrownianBridge.yml'

training:
  batch_size: 16
  n_epochs: 200
  n_iters: 50000001

data:
  dataset: "fish"
  image_size: 128
  channels: 3
  logit_transform: False
