training:
  batch_size: 16
  n_epochs: 200
  n_iters: 50000001

data:
  # dataset: "cityscape_pairs"
  dataset: 'fish'
  image_size: 128
  channels: 3
  logit_transform: False

model:
  dim: 64
  # dim_mults: (1, 2, 4, 8)
  dim_mults: !!python/tuple
    - 1
    - 2
    - 4
    - 8
  n_steps: 1000
  loss_type: 'l2'

optimizer:
  weight_decay: 0.000
  optimizer: 'Adam'
  lr: 0.0001
  beta1: 0.9